#https://docs.rs/i3status-rs/latest/i3status_rs/blocks/index.html

[theme]
theme = "gruvbox-light"

[icons]
icons = "material-nf"

[[block]]
block = "music"

[[block]]
block = "net"
format_alt = "$ssid $signal_strength"
interval = 1

[[block]]
block = "disk_space"
#path = "/"
#info_type = "available"
alert_unit = "GB"
warning = 20.0
alert = 10.0

[[block]]
block = "docker"
format = "$icon $running/$total"

[[block]]
block = "memory"
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "$icon$frequency($utilization)"

[[block]]
block = "load"
interval = 1

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pulsemixer"

[[block]]
block = "pomodoro"
notify_cmd = "notifysend '{msg}'"

[[block]]
block = "time"
interval = 1
format = "$timestamp.datetime(f:'%a %Y-%m-%d %T')"

[[block]]
block = "battery"
driver = "upower"
