theme = "gruvbox-light"
icons = "awesome"

#[[block]]
#block = "focused_window"
#max_width = 24
#show_marks = "visible"

[[block]]
block = "music"
max_width = 10
buttons = ["play", "next"]

[[block]]
block = "net"
format = "{speed_up;K*B}{speed_down;K*B}"
# format_alt = "{ssid} {signal_strength}"
interval = 1
hide_missing = true
hide_inactive = true

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0

[[block]]
block = "docker"
format = "{running}/{total}"

[[block]]
block = "memory"
format_mem = "{mem_used:4*B}/{mem_total:4*B}"
format_swap = "{swap_used:4*B}/{swap_total:4*B}"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "{utilization:02} {frequency}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "pomodoro"
notifier = "notifysend"

[[block]]
block = "time"
interval = 1
format = "%a %Y-%m-%d %T"
