[icons]
# font awesome
TelegramDesktop = ""
firefox = ""
Alacritty = ""
Termite = ""
Thunderbird = ""
Gpick = ""
Nautilus = "📘"
# smile emoji
MyNiceProgram = "😛"

[aliases]
TelegramDesktop = "Telegram"
"Org\\.gnome\\.Nautilus" = "Nautilus"

[general]
separator = "  "
default_icon = "_>"
wm_property = "class"

[options]
remove_duplicates = true
no_names = true
no_icon_names = false
